Update to polkadot-v1.1.0
paritytech/frontier-parachain-template pull request #34
Opened 2023-10-26 06:21 UTC by weezy20

Work in Progress

2023-11-02 11:41 UTC, Moliholy commented
@weezy20 cannot build with `--features runtime-benchmarks`.

2023-11-02 15:29 UTC, Moliholy requested changes

2023-11-02 16:25 UTC, Moliholy commented
@weezy20 after my last commit it should build with `all-features` enabled and pass all the tests.

2023-11-03 06:04 UTC, weezy20 commented on docs/zombienet.md
> +⚠️ Note: The path of the polkadot executable used there is `./bin/polkadot` which means you need to have a folder called `bin` inside the repository directory which contains your compiled polkadot bi
I agree

2023-11-03 06:08 UTC, weezy20 commented on node/src/service.rs
> +		authoring_duration: Duration::from_millis(500),
I believe this is the time that's spent for executing a parachain block which is 0.5 seconds, same as the previous block time. [Reference](https://github.com/paritytech/polkadot-sdk/blob/15a34838819f09f3bcfb3c05c08fb53934d8efc4/cumulus/parachain-template/node/src/service.rs#L413)

2023-11-03 12:27 UTC, Moliholy commented on node/src/service.rs
> +		authoring_duration: Duration::from_millis(500),
Perfect then. Thanks for clarifying 👍

2023-11-03 12:34 UTC, Moliholy approved these changes

2023-11-09 15:26 UTC, merged